Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/4wbq0jwhc0hcx499ma4q8ks88shfim2l-dm-tree-0.1.8.tar.gz
source root is dm-tree-0.1.8
setting SOURCE_DATE_EPOCH to timestamp 1671356145 of file dm-tree-0.1.8/setup.cfg
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing pipBuildPhase
Creating a wheel...
[33mWARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.[0m[33m
[0mProcessing /build/dm-tree-0.1.8
  Running command python setup.py egg_info
  running egg_info
  creating /build/pip-pip-egg-info-bh58ceei/dm_tree.egg-info
  writing /build/pip-pip-egg-info-bh58ceei/dm_tree.egg-info/PKG-INFO
  writing dependency_links to /build/pip-pip-egg-info-bh58ceei/dm_tree.egg-info/dependency_links.txt
  writing top-level names to /build/pip-pip-egg-info-bh58ceei/dm_tree.egg-info/top_level.txt
  writing manifest file '/build/pip-pip-egg-info-bh58ceei/dm_tree.egg-info/SOURCES.txt'
  reading manifest file '/build/pip-pip-egg-info-bh58ceei/dm_tree.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'WORKSPACE'
  warning: no files found matching '*.cpp' under directory '.'
  warning: no files found matching '*.sh' under directory '.'
  warning: no files found matching '*.cmake' under directory '.'
  adding license file 'LICENSE'
  writing manifest file '/build/pip-pip-egg-info-bh58ceei/dm_tree.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... [?25l[?25hdone
Building wheels for collected packages: dm-tree
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-311
  creating build/lib.linux-x86_64-cpython-311/tree
  copying tree/tree_benchmark.py -> build/lib.linux-x86_64-cpython-311/tree
  copying tree/__init__.py -> build/lib.linux-x86_64-cpython-311/tree
  copying tree/tree_test.py -> build/lib.linux-x86_64-cpython-311/tree
  copying tree/sequence.py -> build/lib.linux-x86_64-cpython-311/tree
  running build_ext
  Traceback (most recent call last):
    File "/build/dm-tree-0.1.8/setup.py", line 77, in _check_build_environment
      subprocess.check_call(['cmake', '--version'])
    File "/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g-python3-3.11.6/lib/python3.11/subprocess.py", line 408, in check_call
      retcode = call(*popenargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g-python3-3.11.6/lib/python3.11/subprocess.py", line 389, in call
      with Popen(*popenargs, **kwargs) as p:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g-python3-3.11.6/lib/python3.11/subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g-python3-3.11.6/lib/python3.11/subprocess.py", line 1950, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/build/dm-tree-0.1.8/setup.py", line 124, in <module>
      setuptools.setup(
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
      super().run_command(command)
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/nix/store/xyybi21di6ab74k3xzf1hiv7f2m80cah-python3.11-wheel-0.41.1/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 349, in run
      self.run_command("build")
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
      super().run_command(command)
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
      super().run_command(command)
    File "/nix/store/6dsx7y855a79l3ynz9vpk0y2fddyl5pj-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/build/dm-tree-0.1.8/setup.py", line 70, in run
      self._check_build_environment()
    File "/build/dm-tree-0.1.8/setup.py", line 80, in _check_build_environment
      raise RuntimeError(
  RuntimeError: CMake must be installed to build the following extensions: _tree
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31mÃ—[0m [32mpython setup.py bdist_wheel[0m did not run successfully.
  [31mâ”‚[0m exit code: [1;36m1[0m
  [31mâ•°â”€>[0m See above for output.
  
  [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
  [1;35mfull command[0m: [34m/nix/store/5k91mg4qjylxbfvrv748smfh51ppjq0g-python3-3.11.6/bin/python3.11 -u -c '[0m
[34m  exec(compile('"'"''"'"''"'"'[0m
[34m  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py[0m
[34m  #[0m
[34m  # - It imports setuptools before invoking setup.py, to enable projects that directly[0m
[34m  #   import from `distutils.core` to work with newer packaging standards.[0m
[34m  # - It provides a clear error message when setuptools is not installed.[0m
[34m  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so[0m
[34m  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:[0m
[34m  #     manifest_maker: standard file '"'"'-c'"'"' not found".[0m
[34m  # - It generates a shim setup.py, for handling setup.cfg-only projects.[0m
[34m  import os, sys, tokenize[0m
[34m  [0m
[34m  try:[0m
[34m      import setuptools[0m
[34m  except ImportError as error:[0m
[34m      print([0m
[34m          "ERROR: Can not execute `setup.py` since setuptools is not available in "[0m
[34m          "the build environment.",[0m
[34m          file=sys.stderr,[0m
[34m      )[0m
[34m      sys.exit(1)[0m
[34m  [0m
[34m  __file__ = %r[0m
[34m  sys.argv[0] = __file__[0m
[34m  [0m
[34m  if os.path.exists(__file__):[0m
[34m      filename = __file__[0m
[34m      with tokenize.open(__file__) as f:[0m
[34m          setup_py_code = f.read()[0m
[34m  else:[0m
[34m      filename = "<auto-generated setuptools caller>"[0m
[34m      setup_py_code = "from setuptools import setup; setup()"[0m
[34m  [0m
[34m  exec(compile(setup_py_code, filename, "exec"))[0m
[34m  '"'"''"'"''"'"' % ('"'"'/build/dm-tree-0.1.8/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /build/pip-wheel-usm22eox[0m
  [1;35mcwd[0m: /build/dm-tree-0.1.8/
  Building wheel for dm-tree (setup.py) ... [?25lerror
[31m  ERROR: Failed building wheel for dm-tree[0m[31m
[0m[?25h  Running setup.py clean for dm-tree
  Running command python setup.py clean
  running clean
  removing 'build/lib.linux-x86_64-cpython-311' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.11' does not exist -- can't clean it
  removing 'build'
Failed to build dm-tree
[31mERROR: Failed to build one or more wheels[0m[31m
[0m