Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/9v4y5iy0fsr1qm70sck9y104p9a7skra-twisted-24.3.0.tar.gz
source root is twisted-24.3.0
setting SOURCE_DATE_EPOCH to timestamp 1580601600 of file twisted-24.3.0/tox.ini
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
Removing path dependencies
Finished removing path dependencies
Removing git dependencies
Finished removing git dependencies
Removing wheel-url dependencies
Finished removing wheel-url dependencies
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing pipBuildPhase
Creating a wheel...
[33mWARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.[0m[33m
[0mProcessing /build/twisted-24.3.0
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/nix/store/rn7z8xvfhglhl1k8grv7qjcfc8773x76-python3.11-pip-23.3.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/nix/store/rn7z8xvfhglhl1k8grv7qjcfc8773x76-python3.11-pip-23.3.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/rn7z8xvfhglhl1k8grv7qjcfc8773x76-python3.11-pip-23.3.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/b19ijwz33b9q1s18va5r5h15klz46g8n-python3.11-hatchling-1.21.1/lib/python3.11/site-packages/hatchling/build.py", line 58, in build_wheel
      return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/b19ijwz33b9q1s18va5r5h15klz46g8n-python3.11-hatchling-1.21.1/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
      self.metadata.validate_fields()
    File "/nix/store/b19ijwz33b9q1s18va5r5h15klz46g8n-python3.11-hatchling-1.21.1/lib/python3.11/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
      _ = self.version
          ^^^^^^^^^^^^
    File "/nix/store/b19ijwz33b9q1s18va5r5h15klz46g8n-python3.11-hatchling-1.21.1/lib/python3.11/site-packages/hatchling/metadata/core.py", line 128, in version
      self._version = self._get_version()
                      ^^^^^^^^^^^^^^^^^^^
    File "/nix/store/b19ijwz33b9q1s18va5r5h15klz46g8n-python3.11-hatchling-1.21.1/lib/python3.11/site-packages/hatchling/metadata/core.py", line 222, in _get_version
      core_metadata = self.core
                      ^^^^^^^^^
    File "/nix/store/b19ijwz33b9q1s18va5r5h15klz46g8n-python3.11-hatchling-1.21.1/lib/python3.11/site-packages/hatchling/metadata/core.py", line 166, in core
      metadata_hooks = self.hatch.metadata.hooks
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/b19ijwz33b9q1s18va5r5h15klz46g8n-python3.11-hatchling-1.21.1/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1555, in hooks
      raise UnknownPluginError(message)
  hatchling.plugin.exceptions.UnknownPluginError: Unknown metadata hook: fancy-pypi-readme
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31mÃ—[0m [32mPreparing metadata [0m[1;32m([0m[32mpyproject.toml[0m[1;32m)[0m did not run successfully.
  [31mâ”‚[0m exit code: [1;36m1[0m
  [31mâ•°â”€>[0m See above for output.
  
  [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
  [1;35mfull command[0m: [34m/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/bin/python3.11 /nix/store/rn7z8xvfhglhl1k8grv7qjcfc8773x76-python3.11-pip-23.3.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpiq45j3yv[0m
  [1;35mcwd[0m: /build/twisted-24.3.0
  Preparing metadata (pyproject.toml) ... [?25l[?25herror
[1;31merror[0m: [1mmetadata-generation-failed[0m

[31mÃ—[0m Encountered error while generating package metadata.
[31mâ•°â”€>[0m See above for output.

[1;35mnote[0m: This is an issue with the package mentioned above, not pip.
[1;36mhint[0m: See above for details.
